//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gabinet.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GabinetEntities : DbContext
    {
        public GabinetEntities()
            : base("name=GabinetEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<godziny> godziny { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<uzytkownik> uzytkownik { get; set; }
        public virtual DbSet<uslugi> uslugi { get; set; }
        public virtual DbSet<klienci> klienci { get; set; }
        public virtual DbSet<uzytkownik_usluga> uzytkownik_usluga { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<wizyty> wizyty { get; set; }
    }
}
