//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gabinet.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class wizyty
    {
        public int wizyty_id { get; set; }
        public Nullable<int> klienci_id { get; set; }
        public Nullable<int> uslugi_id { get; set; }
        public Nullable<int> uzytkownik_id { get; set; }
        public Nullable<System.DateTime> rezerwacja_od { get; set; }
        public Nullable<System.DateTime> rezerwacja_do { get; set; }
        public Nullable<int> status_id { get; set; }
        public Nullable<System.DateTime> modyfikacja { get; set; }
    
        public virtual klienci klienci { get; set; }
        public virtual status status { get; set; }
        public virtual uslugi uslugi { get; set; }
        public virtual uzytkownik uzytkownik { get; set; }
    }
}
