//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gabinet.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class godziny
    {
        public int godziny_id { get; set; }
        public int uzytkownik_id { get; set; }
        public Nullable<System.TimeSpan> pon_od { get; set; }
        public Nullable<System.TimeSpan> pon_do { get; set; }
        public Nullable<System.TimeSpan> wt_od { get; set; }
        public Nullable<System.TimeSpan> wt_do { get; set; }
        public Nullable<System.TimeSpan> sr_od { get; set; }
        public Nullable<System.TimeSpan> sr_do { get; set; }
        public Nullable<System.TimeSpan> czw_od { get; set; }
        public Nullable<System.TimeSpan> czw_do { get; set; }
        public Nullable<System.TimeSpan> pt_od { get; set; }
        public Nullable<System.TimeSpan> pt_do { get; set; }
        public Nullable<System.TimeSpan> sb_od { get; set; }
        public Nullable<System.TimeSpan> sb_do { get; set; }
        public Nullable<System.TimeSpan> nd_od { get; set; }
        public Nullable<System.TimeSpan> nd_do { get; set; }
    
        public virtual uzytkownik uzytkownik { get; set; }
    }
}
