//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gabinet.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class klienci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public klienci()
        {
            this.wizyty = new HashSet<wizyty>();
        }
    
        public int klienci_id { get; set; }
        public string imie { get; set; }
        public string nazwisko { get; set; }
        public string email { get; set; }
        public string telefon { get; set; }
        public string ulica { get; set; }
        public string numerDomu { get; set; }
        public string miejscowosc { get; set; }
        public string kodPocztowy { get; set; }
        public Nullable<System.DateTime> modyfikacja { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<wizyty> wizyty { get; set; }
    }
}
